//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppConfigurations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppConfigurations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AppConfigurations", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ImgClientLogo.png.
        /// </summary>
        internal static string Client_Logo {
            get {
                return ResourceManager.GetString("Client_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string Client_Logo_Status {
            get {
                return ResourceManager.GetString("Client_Logo_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Color_Error {
            get {
                return ResourceManager.GetString("Color_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Color_Success {
            get {
                return ResourceManager.GetString("Color_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to border:0px solid Red;.
        /// </summary>
        internal static string Color_Table_Error {
            get {
                return ResourceManager.GetString("Color_Table_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to border:0px solid Green;.
        /// </summary>
        internal static string Color_Table_Success {
            get {
                return ResourceManager.GetString("Color_Table_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/no.png.
        /// </summary>
        internal static string Image_Error {
            get {
                return ResourceManager.GetString("Image_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/Images/yes.png.
        /// </summary>
        internal static string Image_Success {
            get {
                return ResourceManager.GetString("Image_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2013 Examity. All Rights Reserved..
        /// </summary>
        internal static string Label_CopyrightInfo {
            get {
                return ResourceManager.GetString("Label_CopyrightInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support@examity.com.
        /// </summary>
        internal static string Label_SupportEmail {
            get {
                return ResourceManager.GetString("Label_SupportEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web20.
        /// </summary>
        internal static string Skin_Current {
            get {
                return ResourceManager.GetString("Skin_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string Student_MyProfile_Validate_Exams {
            get {
                return ResourceManager.GetString("Student_MyProfile_Validate_Exams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string Student_MyProfile_Validate_PhotoIdentity {
            get {
                return ResourceManager.GetString("Student_MyProfile_Validate_PhotoIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string Student_MyProfile_Validate_Sequestions {
            get {
                return ResourceManager.GetString("Student_MyProfile_Validate_Sequestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string Student_MyProfile_Validate_Timezone {
            get {
                return ResourceManager.GetString("Student_MyProfile_Validate_Timezone", resourceCulture);
            }
        }
    }
}
