//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppHelpContent {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppHelpContent() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AppHelpContent", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;&lt;a href=&quot;CourseDetails.aspx&quot;&gt;Manage course and exam data&lt;/a&gt;&lt;/li&gt;.
        /// </summary>
        internal static string Admin_Home_CoursesAndExams_Body {
            get {
                return ResourceManager.GetString("Admin_Home_CoursesAndExams_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses/Exams.
        /// </summary>
        internal static string Admin_Home_CoursesAndExams_Head {
            get {
                return ResourceManager.GetString("Admin_Home_CoursesAndExams_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;&lt;a href=&quot;ExamStatus.aspx&quot;&gt;Manage exam status&lt;/a&gt;&lt;/li&gt;.
        /// </summary>
        internal static string Admin_Home_ExamStatus_Body {
            get {
                return ResourceManager.GetString("Admin_Home_ExamStatus_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Status.
        /// </summary>
        internal static string Admin_Home_ExamStatus_Head {
            get {
                return ResourceManager.GetString("Admin_Home_ExamStatus_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;&lt;a href=&quot;#&quot;&gt;Manage exam and date exception requests&lt;/a&gt;&lt;/li&gt;.
        /// </summary>
        internal static string Admin_Home_ExceptionRequests_Body {
            get {
                return ResourceManager.GetString("Admin_Home_ExceptionRequests_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Requests.
        /// </summary>
        internal static string Admin_Home_ExceptionRequests_Head {
            get {
                return ResourceManager.GetString("Admin_Home_ExceptionRequests_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;&lt;a href=&quot;Providers.aspx&quot;&gt;Manage Providers&lt;/a&gt;&lt;/li&gt;.
        /// </summary>
        internal static string Admin_Home_Providers_Body {
            get {
                return ResourceManager.GetString("Admin_Home_Providers_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providers.
        /// </summary>
        internal static string Admin_Home_Providers_Head {
            get {
                return ResourceManager.GetString("Admin_Home_Providers_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;&lt;a href=&quot;Reports.aspx&quot;&gt;Exam status report&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;Reports.aspx&quot;&gt;Student data report&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;Reports.aspx&quot;&gt;Course &amp; exam details report&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;Reports.aspx&quot;&gt;Voilation report&lt;/a&gt;&lt;/li&gt;.
        /// </summary>
        internal static string Admin_Home_Reports_Body {
            get {
                return ResourceManager.GetString("Admin_Home_Reports_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Admin_Home_Reports_Head {
            get {
                return ResourceManager.GetString("Admin_Home_Reports_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;&lt;a href=&quot;Students.aspx&quot;&gt;Manage student data&lt;/a&gt;&lt;/li&gt;.
        /// </summary>
        internal static string Admin_Home_Students_Body {
            get {
                return ResourceManager.GetString("Admin_Home_Students_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        internal static string Admin_Home_Students_Head {
            get {
                return ResourceManager.GetString("Admin_Home_Students_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;&lt;li&gt;Auditor can change the password by providing old and new password.&lt;/li&gt;&lt;br /&gt;&lt;/ul&gt;&lt;strong&gt;Note :&lt;/strong&gt; All the changes/updates made in this page will reflect in your original records.&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;.
        /// </summary>
        internal static string Auditor_MyProfile {
            get {
                return ResourceManager.GetString("Auditor_MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;strong&gt;EDUCATION&lt;/strong&gt;&lt;br /&gt;&lt;br /&gt;The next generation delivery of proctoring solutions will have a huge impact in Education provider space to enable them being competitive&lt;br /&gt;Education industry regulations are a key factor in enabling the Remote Proctoring solution.&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&lt;strong&gt;CERTIFICATION&lt;/strong&gt;&lt;/p&gt;&lt;p&gt;Numerous certification programs are working at enabling the remote test process to match student needs for convenience and flexibility.&lt;/p&gt;&lt;p&gt;Examity has executed educ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Common_ChangePassword {
            get {
                return ResourceManager.GetString("Common_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;strong&gt;Examity™ &lt;/strong&gt;is the leading remote proctoring service worldwide.  Our end-to-end solution includes authentication, live monitoring, recording and auditing.&lt;br /&gt;&lt;br /&gt;Test-takers enjoy a seamless experience anytime, anywhere with lot of flexibility.&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;.
        /// </summary>
        internal static string Common_Login {
            get {
                return ResourceManager.GetString("Common_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;&lt;li&gt;Proctor can change the password by providing old and new password.&lt;/li&gt;&lt;br /&gt;&lt;/ul&gt;&lt;strong&gt;Note :&lt;/strong&gt; All the changes/updates made in this page will reflect in your original records.&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;.
        /// </summary>
        internal static string Proctor_Myprofile {
            get {
                return ResourceManager.GetString("Proctor_Myprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;&lt;a href=&quot;CourseDetails.aspx&quot;&gt;Manage course and exam data&lt;/a&gt;&lt;/li&gt;.
        /// </summary>
        internal static string Provider_Home_CoursesAndExams_Body {
            get {
                return ResourceManager.GetString("Provider_Home_CoursesAndExams_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses/Exams.
        /// </summary>
        internal static string Provider_Home_CoursesAndExams_Head {
            get {
                return ResourceManager.GetString("Provider_Home_CoursesAndExams_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;&lt;a href=&quot;ExamStatus.aspx&quot;&gt;Manage exam status&lt;/a&gt;&lt;/li&gt;.
        /// </summary>
        internal static string Provider_Home_ExamStatus_Body {
            get {
                return ResourceManager.GetString("Provider_Home_ExamStatus_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Status.
        /// </summary>
        internal static string Provider_Home_ExamStatus_Head {
            get {
                return ResourceManager.GetString("Provider_Home_ExamStatus_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;&lt;a href=&quot;#&quot;&gt;Manage exam and date exception requests&lt;/a&gt;&lt;/li&gt;.
        /// </summary>
        internal static string Provider_Home_ExceptionRequests_Body {
            get {
                return ResourceManager.GetString("Provider_Home_ExceptionRequests_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception Requests.
        /// </summary>
        internal static string Provider_Home_ExceptionRequests_Head {
            get {
                return ResourceManager.GetString("Provider_Home_ExceptionRequests_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;&lt;a href=&quot;Reports.aspx&quot;&gt;Exam status report&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;Reports.aspx&quot;&gt;Student data report&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;Reports.aspx&quot;&gt;Course &amp; exam details report&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;Reports.aspx&quot;&gt;Voilation report&lt;/a&gt;&lt;/li&gt;.
        /// </summary>
        internal static string Provider_Home_Reports_Body {
            get {
                return ResourceManager.GetString("Provider_Home_Reports_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Provider_Home_Reports_Head {
            get {
                return ResourceManager.GetString("Provider_Home_Reports_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;&lt;a href=&quot;Students.aspx&quot;&gt;Manage student data&lt;/a&gt;&lt;/li&gt;.
        /// </summary>
        internal static string Provider_Home_Students_Body {
            get {
                return ResourceManager.GetString("Provider_Home_Students_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        internal static string Provider_Home_Students_Head {
            get {
                return ResourceManager.GetString("Provider_Home_Students_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;&lt;li&gt;Please select &quot; I agree &quot; option to agree with all the agreements and click on “Next” button.&lt;/li&gt;&lt;br /&gt;&lt;br /&gt;&lt;li&gt;&quot;Next&quot; button will redirect to the webcam configuration page.&lt;/li&gt;&lt;br /&gt;&lt;br /&gt;&lt;/ul&gt;.
        /// </summary>
        internal static string Student_Agreements {
            get {
                return ResourceManager.GetString("Student_Agreements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;How do I schedule for an exam ?&lt;/strong&gt;&lt;ul&gt;&lt;li&gt;You can schedule at any timeslot that best suits you&lt;/li&gt;&lt;li&gt;You can schedule for an exam 48 hours before the exam&lt;/li&gt;&lt;li&gt;If a slot is grayed out, its not a system issue. It just means that slot is full&lt;/li&gt;&lt;li&gt;Select a preferred date (grayed dates mean they can&apos;t be selected)&lt;/li&gt;&lt;li&gt;Select the time that suits you best.&lt;/li&gt;&lt;/ul&gt;&lt;strong&gt;What happens after I schedule ?&lt;/strong&gt;&lt;ul&gt;&lt;li&gt;You will get an email confirming your schedule&lt;/li&gt;&lt;li&gt;In the email [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Student_ExamDetailsConfirmation {
            get {
                return ResourceManager.GetString("Student_ExamDetailsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;&lt;a href=&quot;#&quot;&gt;System readiness&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;#&quot;&gt;Upload ID&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;#&quot;&gt;Enter Security Questions&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;#&quot;&gt;Confirm Time Zone&lt;/a&gt;&lt;/li&gt;.
        /// </summary>
        internal static string Student_Home_ControlPanel_Body {
            get {
                return ResourceManager.GetString("Student_Home_ControlPanel_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        internal static string Student_Home_ControlPanel_Head {
            get {
                return ResourceManager.GetString("Student_Home_ControlPanel_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;&lt;a href=&quot;ScheduleExam.aspx&quot;&gt;Make appointment&lt;/a&gt;&lt;/li&gt;&lt;li&gt;&lt;a href=&quot;MyExams.aspx&quot;&gt;Change appointment&lt;/a&gt;&lt;/li&gt;.
        /// </summary>
        internal static string Student_Home_ExamPanel_Body {
            get {
                return ResourceManager.GetString("Student_Home_ExamPanel_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Panel.
        /// </summary>
        internal static string Student_Home_ExamPanel_Head {
            get {
                return ResourceManager.GetString("Student_Home_ExamPanel_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;&lt;li&gt;Overall information of all the exams scheduled by a student can be found here.&lt;/li&gt;&lt;br /&gt;&lt;br /&gt;&lt;li&gt;“ID” and “Exam Name” search fields can be used to search for an exam from the list.&lt;/li&gt;&lt;br /&gt;&lt;br /&gt;&lt;li&gt;Each column can be sorted by clicking on the column name either in the ascending or descending order. &lt;/li&gt;&lt;br /&gt;&lt;br /&gt;&lt;li&gt;&quot;Page Size&quot; field can be used for either expanding or contracting the list of exams.&lt;/li&gt;&lt;br /&gt;&lt;br /&gt;&lt;li&gt;Clicking on a transaction id provides brief information about the exam.&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Student_MyExams {
            get {
                return ResourceManager.GetString("Student_MyExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ul&gt;&lt;li&gt;You can edit/update the Security Questions provided during Registration.&lt;/li&gt;&lt;br /&gt;&lt;li&gt;You can change the password by providing old and new password.&lt;/li&gt;&lt;br /&gt;&lt;li&gt;You can Upload the new Identity.&lt;/li&gt;&lt;br/&gt;&lt;/ul&gt;&lt;strong&gt;Note :&lt;/strong&gt; All the changes/updates made in this page will reflect in your original records and will be continued for the present and future exams that will be created.&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;.
        /// </summary>
        internal static string Student_MyProfile {
            get {
                return ResourceManager.GetString("Student_MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure you save your information before continuing.&lt;br/&gt;Once you have completed the above steps, you can &lt;a href= &apos;ScheduleExam.aspx&apos;&gt;&lt;u&gt;&lt;font color =&apos;blue&apos;&gt;Schedule an Exam&lt;/font&gt;&lt;/u&gt;&lt;/a&gt;.
        /// </summary>
        internal static string Student_MyProfile_ExamInfo {
            get {
                return ResourceManager.GetString("Student_MyProfile_ExamInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;strong&gt;Before Your Register :&lt;/strong&gt;&lt;ul&gt;&lt;li&gt;You will be notified by your school once you are enrolled.&lt;/li&gt;&lt;li&gt;Check with your school and ensure your enrollment is completed.&lt;/li&gt;&lt;/ul&gt;&lt;/p&gt;&lt;p&gt;&lt;strong&gt;During Registration :&lt;/strong&gt;&lt;ul&gt;&lt;li&gt;Enter all information required for Registration&lt;/li&gt;&lt;li&gt;Your email address will be your user ID&lt;/li&gt;&lt;li&gt;You will set your preferred secure password and security questions&lt;/li&gt;&lt;li&gt;Once you register successfully, you will be notified via email by Examity&lt;/li&gt;&lt;/ul&gt;&lt;/p&gt;&lt;p&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Student_Registration {
            get {
                return ResourceManager.GetString("Student_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;How do I start taking an exam ?&lt;/strong&gt;&lt;ul&gt;&lt;li&gt;You will see a list of all scheduled/completed exams on the screen.&lt;/li&gt;&lt;br /&gt;&lt;li&gt;Look for the exam that you want to start and click on the green play button.&lt;/li&gt;&lt;br /&gt;
        ///&lt;li&gt;Follow instructions as prompted by the system.&lt;/li&gt;&lt;br /&gt;&lt;li&gt;Good Luck for your exam !&lt;/li&gt;&lt;/ul&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;&lt;p&gt;&amp;nbsp;&lt;/p&gt;.
        /// </summary>
        internal static string Student_StartAnExam {
            get {
                return ResourceManager.GetString("Student_StartAnExam", resourceCulture);
            }
        }
    }
}
