//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ResMessages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor already exist..
        /// </summary>
        internal static string Admin_AddStudent_Error_AddInstructor {
            get {
                return ResourceManager.GetString("Admin_AddStudent_Error_AddInstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor added successfully..
        /// </summary>
        internal static string Admin_AddStudent_Success_AddInstructor {
            get {
                return ResourceManager.GetString("Admin_AddStudent_Success_AddInstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been reset successfully..
        /// </summary>
        internal static string Admin_ResetPasswordSuccess {
            get {
                return ResourceManager.GetString("Admin_ResetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only cancel the exam when it is  in scheduled status..
        /// </summary>
        internal static string AppointmentDelete {
            get {
                return ResourceManager.GetString("AppointmentDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancelled successfully..
        /// </summary>
        internal static string AppointmentDeleteSuccess {
            get {
                return ResourceManager.GetString("AppointmentDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Note: Cancelling your exam within 24 hours of your scheduled appointment will result in a $5 cancellation fee, and a charge equal to the cost of proctoring your new appointment.  Per university policy, a credit card will be required to pay the outstanding balance on your account when you schedule your next appointment..
        /// </summary>
        internal static string AppointmentDeleteSuccess_LessThan24Hours {
            get {
                return ResourceManager.GetString("AppointmentDeleteSuccess_LessThan24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurs while updating comments..
        /// </summary>
        internal static string Auditor_EditComments_Error_Comments {
            get {
                return ResourceManager.GetString("Auditor_EditComments_Error_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments updated successfully..
        /// </summary>
        internal static string Auditor_Edit_Success_CommentsUpdated {
            get {
                return ResourceManager.GetString("Auditor_Edit_Success_CommentsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection approved successfully..
        /// </summary>
        internal static string Audit_TransApprove {
            get {
                return ResourceManager.GetString("Audit_TransApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval/Rejection failed. Please try again..
        /// </summary>
        internal static string Audit_TransFail {
            get {
                return ResourceManager.GetString("Audit_TransFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction is rejected successfully..
        /// </summary>
        internal static string Audit_TransReject {
            get {
                return ResourceManager.GetString("Audit_TransReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select to approve..
        /// </summary>
        internal static string Audit_TransSelect {
            get {
                return ResourceManager.GetString("Audit_TransSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FairExam &lt;sup style=&quot;font-size:13px;&quot;&gt;®&lt;/sup&gt; Level.
        /// </summary>
        internal static string Common_FairExamLevel {
            get {
                return ResourceManager.GetString("Common_FairExamLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Meeting Credentials &lt;u&gt;&lt;a href=&apos;https://howardcc.instructure.com/login&apos;  target=&quot;_blank&quot;&gt;Click here&lt;/a&gt;&lt;/u&gt;. Please try again..
        /// </summary>
        internal static string Invalid_ClickHere {
            get {
                return ResourceManager.GetString("Invalid_ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is sent to .
        /// </summary>
        internal static string Login_EmailSuccess {
            get {
                return ResourceManager.GetString("Login_EmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your User ID..
        /// </summary>
        internal static string Login_EmailVerify {
            get {
                return ResourceManager.GetString("Login_EmailVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry for the inconvenience. Unable to connect to the DB server..
        /// </summary>
        internal static string Login_InvalidDB {
            get {
                return ResourceManager.GetString("Login_InvalidDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your User ID..
        /// </summary>
        internal static string Login_InvalidEmailID {
            get {
                return ResourceManager.GetString("Login_InvalidEmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid User ID/Password..
        /// </summary>
        internal static string Login_Invalidemail_password {
            get {
                return ResourceManager.GetString("Login_Invalidemail_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password..
        /// </summary>
        internal static string Login_PasswordEnter {
            get {
                return ResourceManager.GetString("Login_PasswordEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are successfully logged out of Examity..
        /// </summary>
        internal static string LogOut_V {
            get {
                return ResourceManager.GetString("LogOut_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm the new password..
        /// </summary>
        internal static string MyProfile_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("MyProfile_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the current password..
        /// </summary>
        internal static string MyProfile_CurrPassword {
            get {
                return ResourceManager.GetString("MyProfile_CurrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to examiBADGE &lt;sup style=&quot;font-size:13px;&quot;&gt;®&lt;/sup&gt;.
        /// </summary>
        internal static string MyProfile_ExamiBADGE {
            get {
                return ResourceManager.GetString("MyProfile_ExamiBADGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to examiKEY &lt;sup style=&quot;font-size:13px;&quot;&gt;®&lt;/sup&gt;.
        /// </summary>
        internal static string MyProfile_ExamiKEY {
            get {
                return ResourceManager.GetString("MyProfile_ExamiKEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to examiKEY &lt;sup style=&quot;font-size:13px;&quot;&gt;®&lt;/sup&gt;  not updated..
        /// </summary>
        internal static string MyProfile_ExamiKEYNotUpdated {
            get {
                return ResourceManager.GetString("MyProfile_ExamiKEYNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to examiKEY &lt;sup style=&quot;font-size:13px;&quot;&gt;®&lt;/sup&gt;  not updated.First Name and Last Name , Re-enter First Name and Last Name must be same..
        /// </summary>
        internal static string MyProfile_ExamiKEYNotUpdated1 {
            get {
                return ResourceManager.GetString("MyProfile_ExamiKEYNotUpdated1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to examiKEY &lt;sup style=&quot;font-size:13px;&quot;&gt;®&lt;/sup&gt; updated successfully..
        /// </summary>
        internal static string MyProfile_ExamiKEYUpdated {
            get {
                return ResourceManager.GetString("MyProfile_ExamiKEYUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 more test to earn your Bronze examiBADGE &lt;sup style=&quot;font-size:13px;&quot;&gt;®&lt;/sup&gt;.
        /// </summary>
        internal static string MYProfile_Exams0 {
            get {
                return ResourceManager.GetString("MYProfile_Exams0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 more tests to earn your Silver examiBADGE &lt;sup style=&quot;font-size:13px;&quot;&gt;®&lt;/sup&gt;.
        /// </summary>
        internal static string MYProfile_Exams1 {
            get {
                return ResourceManager.GetString("MYProfile_Exams1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have earned the distinction of a Platinum  examiBADGE &lt;sup style=&quot;font-size:13px;&quot;&gt;®&lt;/sup&gt;.
        /// </summary>
        internal static string MYProfile_Exams10 {
            get {
                return ResourceManager.GetString("MYProfile_Exams10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 more test to earn your Silver examiBADGE &lt;sup style=&quot;font-size:13px;&quot;&gt;®&lt;/sup&gt;.
        /// </summary>
        internal static string MYProfile_Exams2 {
            get {
                return ResourceManager.GetString("MYProfile_Exams2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 more tests to earn your Gold examiBADGE &lt;sup style=&quot;font-size:13px;&quot;&gt;®&lt;/sup&gt;.
        /// </summary>
        internal static string MYProfile_Exams3 {
            get {
                return ResourceManager.GetString("MYProfile_Exams3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 more test to earn your Gold examiBADGE &lt;sup style=&quot;font-size:13px;&quot;&gt;®&lt;/sup&gt;.
        /// </summary>
        internal static string MYProfile_Exams4 {
            get {
                return ResourceManager.GetString("MYProfile_Exams4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 more tests to earn your Platinum examiBADGE &lt;sup style=&quot;font-size:13px;&quot;&gt;®&lt;/sup&gt;.
        /// </summary>
        internal static string MYProfile_Exams5 {
            get {
                return ResourceManager.GetString("MYProfile_Exams5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 more tests to earn your Platinum examiBADGE &lt;sup style=&quot;font-size:13px;&quot;&gt;®&lt;/sup&gt;.
        /// </summary>
        internal static string MYProfile_Exams6 {
            get {
                return ResourceManager.GetString("MYProfile_Exams6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 more tests to earn your Platinum examiBADGE &lt;sup style=&quot;font-size:13px;&quot;&gt;®&lt;/sup&gt;.
        /// </summary>
        internal static string MYProfile_Exams7 {
            get {
                return ResourceManager.GetString("MYProfile_Exams7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 more tests to earn your Platinum examiBADGE &lt;sup style=&quot;font-size:13px;&quot;&gt;®&lt;/sup&gt;.
        /// </summary>
        internal static string MYProfile_Exams8 {
            get {
                return ResourceManager.GetString("MYProfile_Exams8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 more test to earn your Platinum examiBADGE &lt;sup style=&quot;font-size:13px;&quot;&gt;®&lt;/sup&gt;.
        /// </summary>
        internal static string MYProfile_Exams9 {
            get {
                return ResourceManager.GetString("MYProfile_Exams9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo ID uploaded successfully..
        /// </summary>
        internal static string MyProfile_FileUploadSuccess {
            get {
                return ResourceManager.GetString("MyProfile_FileUploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the new password..
        /// </summary>
        internal static string MyProfile_NewPassword {
            get {
                return ResourceManager.GetString("MyProfile_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password didn’t match..
        /// </summary>
        internal static string Myprofile_PasswordMatch {
            get {
                return ResourceManager.GetString("Myprofile_PasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password has been updated successfully..
        /// </summary>
        internal static string MyProfile_PasswordUpdateSuccess {
            get {
                return ResourceManager.GetString("MyProfile_PasswordUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security questions updated successfully..
        /// </summary>
        internal static string MyProfile_SecquestionsUpdateSuccess {
            get {
                return ResourceManager.GetString("MyProfile_SecquestionsUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to examiKNOW &lt;sup style=&quot;font-size:13px;&quot;&gt;®&lt;/sup&gt;.
        /// </summary>
        internal static string MyProfile_SecurityQuestions {
            get {
                return ResourceManager.GetString("MyProfile_SecurityQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time zone.
        /// </summary>
        internal static string MyProfile_TimeZone {
            get {
                return ResourceManager.GetString("MyProfile_TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account information updation failed. Please try again..
        /// </summary>
        internal static string MyProfile_TimeZoneUpdateFailed {
            get {
                return ResourceManager.GetString("MyProfile_TimeZoneUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account information has been updated successfully..
        /// </summary>
        internal static string MyProfile_TimeZoneUpdateSuccess {
            get {
                return ResourceManager.GetString("MyProfile_TimeZoneUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to examiSHOW  &lt;sup style=&quot;font-size:13px;&quot;&gt;®&lt;/sup&gt;.
        /// </summary>
        internal static string MyProfile_UploadPicture {
            get {
                return ResourceManager.GetString("MyProfile_UploadPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid current password..
        /// </summary>
        internal static string MyProfile_ValidCurrentPassword {
            get {
                return ResourceManager.GetString("MyProfile_ValidCurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added successfully..
        /// </summary>
        internal static string Proctor_AddProctor {
            get {
                return ResourceManager.GetString("Proctor_AddProctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam ID doesn&apos;t exists..
        /// </summary>
        internal static string Proctor_Add_Error_AddMeeting {
            get {
                return ResourceManager.GetString("Proctor_Add_Error_AddMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam session id updated successfully..
        /// </summary>
        internal static string Proctor_Add_Success_AddMeeting {
            get {
                return ResourceManager.GetString("Proctor_Add_Success_AddMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add  comments..
        /// </summary>
        internal static string Proctor_CommentsMandate {
            get {
                return ResourceManager.GetString("Proctor_CommentsMandate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while adding proctor name..
        /// </summary>
        internal static string Proctor_Error_AddProctor {
            get {
                return ResourceManager.GetString("Proctor_Error_AddProctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam approved successfully..
        /// </summary>
        internal static string Proctor_ExamApprove {
            get {
                return ResourceManager.GetString("Proctor_ExamApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam has been closed by proctor successfully..
        /// </summary>
        internal static string Proctor_ExamClose {
            get {
                return ResourceManager.GetString("Proctor_ExamClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam is incomplete.
        /// </summary>
        internal static string Proctor_ExamIncomplete {
            get {
                return ResourceManager.GetString("Proctor_ExamIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course ID already exists..
        /// </summary>
        internal static string Provider_CourseEditFailed {
            get {
                return ResourceManager.GetString("Provider_CourseEditFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course details  updated successfully..
        /// </summary>
        internal static string Provider_CourseEditSuccess {
            get {
                return ResourceManager.GetString("Provider_CourseEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course ID already exists..
        /// </summary>
        internal static string Provider_CourseExists {
            get {
                return ResourceManager.GetString("Provider_CourseExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course created successfully..
        /// </summary>
        internal static string Provider_CourseSuccess {
            get {
                return ResourceManager.GetString("Provider_CourseSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully..
        /// </summary>
        internal static string Provider_DeleteEnrollment {
            get {
                return ResourceManager.GetString("Provider_DeleteEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student has been already enrolled for this exam..
        /// </summary>
        internal static string Provider_EnrollStudentExam {
            get {
                return ResourceManager.GetString("Provider_EnrollStudentExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student has been enrolled for an exam successfully..
        /// </summary>
        internal static string Provider_EnrollStudentSuccess {
            get {
                return ResourceManager.GetString("Provider_EnrollStudentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment details updated successfully..
        /// </summary>
        internal static string Provider_EnrollUpdate {
            get {
                return ResourceManager.GetString("Provider_EnrollUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add comments..
        /// </summary>
        internal static string Provider_ExamComments {
            get {
                return ResourceManager.GetString("Provider_ExamComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam has been deleted successfully..
        /// </summary>
        internal static string Provider_ExamDeleteSuccess {
            get {
                return ResourceManager.GetString("Provider_ExamDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New exam details have been saved successfully..
        /// </summary>
        internal static string Provider_ExamDetailsSuccess {
            get {
                return ResourceManager.GetString("Provider_ExamDetailsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter course name..
        /// </summary>
        internal static string Provider_ExamDetCourse {
            get {
                return ResourceManager.GetString("Provider_ExamDetCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter exam name..
        /// </summary>
        internal static string Provider_ExamDetExam {
            get {
                return ResourceManager.GetString("Provider_ExamDetExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam name already exists..
        /// </summary>
        internal static string Provider_ExamExists {
            get {
                return ResourceManager.GetString("Provider_ExamExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New exam details saved successfully.
        /// </summary>
        internal static string Provider_ExamUpdateSuccess {
            get {
                return ResourceManager.GetString("Provider_ExamUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid URL..
        /// </summary>
        internal static string Provider_ExamURL {
            get {
                return ResourceManager.GetString("Provider_ExamURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes can not be empty..
        /// </summary>
        internal static string Provider_Notes {
            get {
                return ResourceManager.GetString("Provider_Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules can not be empty..
        /// </summary>
        internal static string Provider_Rules {
            get {
                return ResourceManager.GetString("Provider_Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student has been enrolled successfully..
        /// </summary>
        internal static string Provider_StudentEnroll {
            get {
                return ResourceManager.GetString("Provider_StudentEnroll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email enrolled successfully..
        /// </summary>
        internal static string Provider_StudentEnrollUpdateSuccess {
            get {
                return ResourceManager.GetString("Provider_StudentEnrollUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student already exists..
        /// </summary>
        internal static string Provider_StudentExists {
            get {
                return ResourceManager.GetString("Provider_StudentExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid details..
        /// </summary>
        internal static string Provider_StudentUpdateFail {
            get {
                return ResourceManager.GetString("Provider_StudentUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student details updated successfully..
        /// </summary>
        internal static string Provider_StudentUpdateSuccess {
            get {
                return ResourceManager.GetString("Provider_StudentUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student deletion failed. Please try again..
        /// </summary>
        internal static string Provider_UserDelFail {
            get {
                return ResourceManager.GetString("Provider_UserDelFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletion failed as student has pending exams..
        /// </summary>
        internal static string Provider_UserDelPending {
            get {
                return ResourceManager.GetString("Provider_UserDelPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student deleted successfully..
        /// </summary>
        internal static string Provider_UserDelSuccess {
            get {
                return ResourceManager.GetString("Provider_UserDelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address..
        /// </summary>
        internal static string Provider_Useremailid {
            get {
                return ResourceManager.GetString("Provider_Useremailid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter student first name..
        /// </summary>
        internal static string Provider_UserFirstName {
            get {
                return ResourceManager.GetString("Provider_UserFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter student last name..
        /// </summary>
        internal static string Provider_UserLastName {
            get {
                return ResourceManager.GetString("Provider_UserLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your phone number..
        /// </summary>
        internal static string Provider_UserPhone {
            get {
                return ResourceManager.GetString("Provider_UserPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email address.
        /// </summary>
        internal static string Provider_UserValidemail {
            get {
                return ResourceManager.GetString("Provider_UserValidemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your password..
        /// </summary>
        internal static string Reg_ConfirmPassword {
            get {
                return ResourceManager.GetString("Reg_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your phone number..
        /// </summary>
        internal static string Reg_EnterPhone {
            get {
                return ResourceManager.GetString("Reg_EnterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your prefered phone number.
        /// </summary>
        internal static string Reg_EnterPrefPhone {
            get {
                return ResourceManager.GetString("Reg_EnterPrefPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter first name..
        /// </summary>
        internal static string Reg_FirstName {
            get {
                return ResourceManager.GetString("Reg_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select gender..
        /// </summary>
        internal static string Reg_GenderSel {
            get {
                return ResourceManager.GetString("Reg_GenderSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter last name..
        /// </summary>
        internal static string Reg_LastName {
            get {
                return ResourceManager.GetString("Reg_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All fields are mandatory..
        /// </summary>
        internal static string Reg_Mandatoryfields {
            get {
                return ResourceManager.GetString("Reg_Mandatoryfields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student details are not found.  Please contact exam Instructor..
        /// </summary>
        internal static string Reg_NoStudentDet {
            get {
                return ResourceManager.GetString("Reg_NoStudentDet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password..
        /// </summary>
        internal static string Reg_PasswordEnter {
            get {
                return ResourceManager.GetString("Reg_PasswordEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password didn’t match..
        /// </summary>
        internal static string Reg_PasswordMatch {
            get {
                return ResourceManager.GetString("Reg_PasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter answer..
        /// </summary>
        internal static string Reg_SecAnswerEnter {
            get {
                return ResourceManager.GetString("Reg_SecAnswerEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a security question..
        /// </summary>
        internal static string Reg_SecQuestionEnter {
            get {
                return ResourceManager.GetString("Reg_SecQuestionEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your registration did not go through. Please review registration instructions provided on this screen..
        /// </summary>
        internal static string Reg_StudentRegFail {
            get {
                return ResourceManager.GetString("Reg_StudentRegFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student registered successfully..
        /// </summary>
        internal static string Reg_StudentRegSuccess {
            get {
                return ResourceManager.GetString("Reg_StudentRegSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select time zone..
        /// </summary>
        internal static string Reg_TimeZoneSel {
            get {
                return ResourceManager.GetString("Reg_TimeZoneSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload your Photo ID..
        /// </summary>
        internal static string Reg_Uploadfile {
            get {
                return ResourceManager.GetString("Reg_Uploadfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The height of the image is exceeding 300, please select another image with 300 x 300 dimensions..
        /// </summary>
        internal static string Reg_Uploadfileheight {
            get {
                return ResourceManager.GetString("Reg_Uploadfileheight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size of the file uploaded is too large, please upload the file less than 1MB size limit..
        /// </summary>
        internal static string Reg_Uploadfilesize {
            get {
                return ResourceManager.GetString("Reg_Uploadfilesize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists..
        /// </summary>
        internal static string Reg_UserExists {
            get {
                return ResourceManager.GetString("Reg_UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter user name..
        /// </summary>
        internal static string Reg_UserName {
            get {
                return ResourceManager.GetString("Reg_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload .jpg,.png,.gif,.bmp,.jpeg files only..
        /// </summary>
        internal static string Reg_Validuploadfiles {
            get {
                return ResourceManager.GetString("Reg_Validuploadfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email address.
        /// </summary>
        internal static string Reg_ValidUserName {
            get {
                return ResourceManager.GetString("Reg_ValidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With On-demand scheduling option exam can be rescheduled within 24 hours..
        /// </summary>
        internal static string Reschedule_24hoursValidation {
            get {
                return ResourceManager.GetString("Reschedule_24hoursValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve rescheduled your exam (ID:.
        /// </summary>
        internal static string Reschedule_Confirmation {
            get {
                return ResourceManager.GetString("Reschedule_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to )!.
        /// </summary>
        internal static string Reschedule_Confirmation1 {
            get {
                return ResourceManager.GetString("Reschedule_Confirmation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam is already in progress. Rescheduling is not allowed..
        /// </summary>
        internal static string Reschedule_ExamProgressValidation {
            get {
                return ResourceManager.GetString("Reschedule_ExamProgressValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam reschedule date should be between .
        /// </summary>
        internal static string Reschedule_ExamStartEndDateValidation {
            get {
                return ResourceManager.GetString("Reschedule_ExamStartEndDateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With On-demand scheduling option exam can be rescheduled within 24 hours..
        /// </summary>
        internal static string ReSchedule_OndemandValidation {
            get {
                return ResourceManager.GetString("ReSchedule_OndemandValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam can not be rescheduled prior to today&apos;s date..
        /// </summary>
        internal static string Reschedule_PriorDateValidation {
            get {
                return ResourceManager.GetString("Reschedule_PriorDateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam already scheduled in current time window. Rescheduling is not allowed..
        /// </summary>
        internal static string Reschedule_TimeWindowValidation {
            get {
                return ResourceManager.GetString("Reschedule_TimeWindowValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With On-demand scheduling option exam can be scheduled within 24 hours..
        /// </summary>
        internal static string Schedule_24hoursValidation {
            get {
                return ResourceManager.GetString("Schedule_24hoursValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve scheduled your exam (ID:.
        /// </summary>
        internal static string Schedule_Confirmation {
            get {
                return ResourceManager.GetString("Schedule_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to )!.
        /// </summary>
        internal static string Schedule_Confirmation1 {
            get {
                return ResourceManager.GetString("Schedule_Confirmation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  cannot be scheduled at this point of time. Exam can be scheduled between .
        /// </summary>
        internal static string Schedule_ExamStartEndDateValidation {
            get {
                return ResourceManager.GetString("Schedule_ExamStartEndDateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With On-demand scheduling option exam can be scheduled within 24 hours..
        /// </summary>
        internal static string Schedule_OndemandValidation {
            get {
                return ResourceManager.GetString("Schedule_OndemandValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam can not be scheduled prior to today&apos;s date..
        /// </summary>
        internal static string Schedule_PriorDateValidation {
            get {
                return ResourceManager.GetString("Schedule_PriorDateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam already scheduled in current time window..
        /// </summary>
        internal static string Schedule_TimeWindowValidation {
            get {
                return ResourceManager.GetString("Schedule_TimeWindowValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are successfully logged out of Examity..
        /// </summary>
        internal static string Session_V {
            get {
                return ResourceManager.GetString("Session_V", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected date/time is Unavailable..
        /// </summary>
        internal static string Slot_Unavailable {
            get {
                return ResourceManager.GetString("Slot_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam start and/or end date is empty. Please contact &lt;u&gt;&lt;a href=&apos;mailto:support@examity.com&apos;  target=&quot;_blank&quot;&gt;Examity Support&lt;/a&gt;&lt;/u&gt; for further assistance..
        /// </summary>
        internal static string StartDateAndEndDateIsEmpty {
            get {
                return ResourceManager.GetString("StartDateAndEndDateIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accept all the agreements..
        /// </summary>
        internal static string Student_Agreements {
            get {
                return ResourceManager.GetString("Student_Agreements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already scheduled an appointment for.
        /// </summary>
        internal static string Student_AnAppointment {
            get {
                return ResourceManager.GetString("Student_AnAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An appointment for the same exam is in.
        /// </summary>
        internal static string Student_AnAppointmentForthesame {
            get {
                return ResourceManager.GetString("Student_AnAppointmentForthesame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can reschedule or cancel your appointment by clicking on the buttons below..
        /// </summary>
        internal static string Student_AreyouSure {
            get {
                return ResourceManager.GetString("Student_AreyouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only start the exam 15 minutes before the scheduled time..
        /// </summary>
        internal static string Student_checkStartTime {
            get {
                return ResourceManager.GetString("Student_checkStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is already scheduled on.
        /// </summary>
        internal static string Student_ExamAlreadyExists {
            get {
                return ResourceManager.GetString("Student_ExamAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is already scheduled at a different time..
        /// </summary>
        internal static string Student_ExamAlreadyExistsElse {
            get {
                return ResourceManager.GetString("Student_ExamAlreadyExistsElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam completed successfully..
        /// </summary>
        internal static string Student_ExamCloseconfirm {
            get {
                return ResourceManager.GetString("Student_ExamCloseconfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tools available..
        /// </summary>
        internal static string Student_ExamDetConfirmNoTools {
            get {
                return ResourceManager.GetString("Student_ExamDetConfirmNoTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your exam has been rescheduled successfully. An email with instructions has been sent to your email address..
        /// </summary>
        internal static string Student_ExamdetConfirmReSchedule {
            get {
                return ResourceManager.GetString("Student_ExamdetConfirmReSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your exam has been scheduled successfully. An email with instructions has been sent to your email address..
        /// </summary>
        internal static string Student_ExamdetConfirmSchedule {
            get {
                return ResourceManager.GetString("Student_ExamdetConfirmSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once the exam is completed, please click on Close Exam button..
        /// </summary>
        internal static string Student_ExamSession_Close {
            get {
                return ResourceManager.GetString("Student_ExamSession_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not close or refresh this window during your exam, or you will lose connection with your proctor..
        /// </summary>
        internal static string Student_ExamSession_NoClose {
            get {
                return ResourceManager.GetString("Student_ExamSession_NoClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect security answers. Please try again..
        /// </summary>
        internal static string Student_InvalidSecAns {
            get {
                return ResourceManager.GetString("Student_InvalidSecAns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please answer all three security questions..
        /// </summary>
        internal static string Student_MyprofileAllthreeAnswers {
            get {
                return ResourceManager.GetString("Student_MyprofileAllthreeAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select all three security questions..
        /// </summary>
        internal static string Student_MyprofileAllthreequestions {
            get {
                return ResourceManager.GetString("Student_MyprofileAllthreequestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete your &lt;a href=&apos;MyProfile.aspx&apos;&gt;&lt;u&gt;&lt;font color=&apos;blue&apos;&gt;Profile &lt;/font&gt;&lt;/u&gt;&lt;/a&gt; for scheduling an exam..
        /// </summary>
        internal static string Student_MyProfileCheck {
            get {
                return ResourceManager.GetString("Student_MyProfileCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select three different security questions.
        /// </summary>
        internal static string Student_MyprofilethreeDifferentQuestions {
            get {
                return ResourceManager.GetString("Student_MyprofilethreeDifferentQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The popup was blocked. You must allow popups to use this site..
        /// </summary>
        internal static string Student_PopupAlert {
            get {
                return ResourceManager.GetString("Student_PopupAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam scheduled successfully..
        /// </summary>
        internal static string Student_ScheduleExam {
            get {
                return ResourceManager.GetString("Student_ScheduleExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer cannot be blank..
        /// </summary>
        internal static string Student_SecAnswerEmpty {
            get {
                return ResourceManager.GetString("Student_SecAnswerEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot schedule a new appointment at this point of time..
        /// </summary>
        internal static string Student_YouCantSchedule {
            get {
                return ResourceManager.GetString("Student_YouCantSchedule", resourceCulture);
            }
        }
    }
}
