//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SecureProctor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecureProctor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SecureProctor", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added By.
        /// </summary>
        internal static string Common_AddedBy {
            get {
                return ResourceManager.GetString("Common_AddedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added On.
        /// </summary>
        internal static string Common_AddedOn {
            get {
                return ResourceManager.GetString("Common_AddedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        internal static string Common_Approve {
            get {
                return ResourceManager.GetString("Common_Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Common_Back {
            get {
                return ResourceManager.GetString("Common_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Common_Clear {
            get {
                return ResourceManager.GetString("Common_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Common_Comments {
            get {
                return ResourceManager.GetString("Common_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incident Time Stamp.
        /// </summary>
        internal static string Common_CommentTime {
            get {
                return ResourceManager.GetString("Common_CommentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Common_Confirm {
            get {
                return ResourceManager.GetString("Common_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Common_Edit {
            get {
                return ResourceManager.GetString("Common_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flag.
        /// </summary>
        internal static string Common_Flag {
            get {
                return ResourceManager.GetString("Common_Flag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Description.
        /// </summary>
        internal static string Common_NoteDesc {
            get {
                return ResourceManager.GetString("Common_NoteDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note ID.
        /// </summary>
        internal static string Common_NoteID {
            get {
                return ResourceManager.GetString("Common_NoteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string Common_Reject {
            get {
                return ResourceManager.GetString("Common_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Description.
        /// </summary>
        internal static string Common_RoleDesc {
            get {
                return ResourceManager.GetString("Common_RoleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuleID.
        /// </summary>
        internal static string Common_RuleID {
            get {
                return ResourceManager.GetString("Common_RuleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Common_Submit {
            get {
                return ResourceManager.GetString("Common_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Common_Upload {
            get {
                return ResourceManager.GetString("Common_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Grid_Header_Cancel {
            get {
                return ResourceManager.GetString("Grid_Header_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Grid_Header_CancelNew {
            get {
                return ResourceManager.GetString("Grid_Header_CancelNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel this Appointment.
        /// </summary>
        internal static string Grid_Header_CancelNewDescription {
            get {
                return ResourceManager.GetString("Grid_Header_CancelNewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course ID.
        /// </summary>
        internal static string Grid_Header_CourseID {
            get {
                return ResourceManager.GetString("Grid_Header_CourseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Name.
        /// </summary>
        internal static string Grid_Header_CourseName {
            get {
                return ResourceManager.GetString("Grid_Header_CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string Grid_Header_EmailAddress {
            get {
                return ResourceManager.GetString("Grid_Header_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroll Date.
        /// </summary>
        internal static string Grid_Header_EnrollmentDate {
            get {
                return ResourceManager.GetString("Grid_Header_EnrollmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroll Status.
        /// </summary>
        internal static string Grid_Header_EnrollmentStatus {
            get {
                return ResourceManager.GetString("Grid_Header_EnrollmentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Date.
        /// </summary>
        internal static string Grid_Header_ExamDate {
            get {
                return ResourceManager.GetString("Grid_Header_ExamDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam ID.
        /// </summary>
        internal static string Grid_Header_ExamID {
            get {
                return ResourceManager.GetString("Grid_Header_ExamID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Name.
        /// </summary>
        internal static string Grid_Header_ExamName {
            get {
                return ResourceManager.GetString("Grid_Header_ExamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FairExam &lt;sup  style=&quot;font-size:12px;&quot;&gt;®&lt;/sup&gt; Level.
        /// </summary>
        internal static string Grid_Header_ExamSecurityLevel {
            get {
                return ResourceManager.GetString("Grid_Header_ExamSecurityLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Grid_Header_ExamStatus {
            get {
                return ResourceManager.GetString("Grid_Header_ExamStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Grid_Header_Green {
            get {
                return ResourceManager.GetString("Grid_Header_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string Grid_Header_Orange {
            get {
                return ResourceManager.GetString("Grid_Header_Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proctor.
        /// </summary>
        internal static string Grid_Header_Proctor {
            get {
                return ResourceManager.GetString("Grid_Header_Proctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor First Name.
        /// </summary>
        internal static string Grid_Header_ProviderFirstName {
            get {
                return ResourceManager.GetString("Grid_Header_ProviderFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor Last Name.
        /// </summary>
        internal static string Grid_Header_ProviderLastName {
            get {
                return ResourceManager.GetString("Grid_Header_ProviderLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor Name.
        /// </summary>
        internal static string Grid_Header_ProviderName {
            get {
                return ResourceManager.GetString("Grid_Header_ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Grid_Header_Red {
            get {
                return ResourceManager.GetString("Grid_Header_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule.
        /// </summary>
        internal static string Grid_Header_ReschduleNew {
            get {
                return ResourceManager.GetString("Grid_Header_ReschduleNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule this Appointment.
        /// </summary>
        internal static string Grid_Header_ReschduleNewDescription {
            get {
                return ResourceManager.GetString("Grid_Header_ReschduleNewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule/Cancel.
        /// </summary>
        internal static string Grid_Header_ReschduleORCancel {
            get {
                return ResourceManager.GetString("Grid_Header_ReschduleORCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule or Cancel.
        /// </summary>
        internal static string Grid_Header_ReschduleORCancelRowDesc {
            get {
                return ResourceManager.GetString("Grid_Header_ReschduleORCancelRowDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule.
        /// </summary>
        internal static string Grid_Header_Reschedule {
            get {
                return ResourceManager.GetString("Grid_Header_Reschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Time.
        /// </summary>
        internal static string Grid_Header_ScheduleTime {
            get {
                return ResourceManager.GetString("Grid_Header_ScheduleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Grid_Header_Select {
            get {
                return ResourceManager.GetString("Grid_Header_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        internal static string Grid_Header_StartTime {
            get {
                return ResourceManager.GetString("Grid_Header_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Grid_Header_Status {
            get {
                return ResourceManager.GetString("Grid_Header_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student First Name.
        /// </summary>
        internal static string Grid_Header_StudentFirstName {
            get {
                return ResourceManager.GetString("Grid_Header_StudentFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Last Name.
        /// </summary>
        internal static string Grid_Header_StudentLastName {
            get {
                return ResourceManager.GetString("Grid_Header_StudentLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name.
        /// </summary>
        internal static string Grid_Header_StudentName {
            get {
                return ResourceManager.GetString("Grid_Header_StudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Grid_Header_TransactionID {
            get {
                return ResourceManager.GetString("Grid_Header_TransactionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string Grid_Header_View {
            get {
                return ResourceManager.GetString("Grid_Header_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Tab_Auditor_Home {
            get {
                return ResourceManager.GetString("Tab_Auditor_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        internal static string Tab_Auditor_Inbox {
            get {
                return ResourceManager.GetString("Tab_Auditor_Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Tab_Auditor_Logout {
            get {
                return ResourceManager.GetString("Tab_Auditor_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string Tab_Auditor_MyProfile {
            get {
                return ResourceManager.GetString("Tab_Auditor_MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed Exams.
        /// </summary>
        internal static string Tab_Auditor_ProcessedExams {
            get {
                return ResourceManager.GetString("Tab_Auditor_ProcessedExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Tab_Auditor_Reports {
            get {
                return ResourceManager.GetString("Tab_Auditor_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Lookup.
        /// </summary>
        internal static string Tab_Auditor_StudentLookUp {
            get {
                return ResourceManager.GetString("Tab_Auditor_StudentLookUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Tab_Proctor_Home {
            get {
                return ResourceManager.GetString("Tab_Proctor_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Tab_Proctor_Logout {
            get {
                return ResourceManager.GetString("Tab_Proctor_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string Tab_Proctor_MyProfile {
            get {
                return ResourceManager.GetString("Tab_Proctor_MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Tab_Proctor_Reports {
            get {
                return ResourceManager.GetString("Tab_Proctor_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student/Exam Lookup.
        /// </summary>
        internal static string Tab_Proctor_StudentExamLookUp {
            get {
                return ResourceManager.GetString("Tab_Proctor_StudentExamLookUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate Auto Proctor.
        /// </summary>
        internal static string Tab_Proctor_ValidateAutoProctor {
            get {
                return ResourceManager.GetString("Tab_Proctor_ValidateAutoProctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate &amp; Proctor.
        /// </summary>
        internal static string Tab_Proctor_ValidateProctor {
            get {
                return ResourceManager.GetString("Tab_Proctor_ValidateProctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Course.
        /// </summary>
        internal static string Tab_Provider_Course {
            get {
                return ResourceManager.GetString("Tab_Provider_Course", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Details.
        /// </summary>
        internal static string Tab_Provider_CourseDetails {
            get {
                return ResourceManager.GetString("Tab_Provider_CourseDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses/Exams.
        /// </summary>
        internal static string Tab_Provider_CoursesExams {
            get {
                return ResourceManager.GetString("Tab_Provider_CoursesExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enroll student.
        /// </summary>
        internal static string Tab_Provider_EnrollStudent {
            get {
                return ResourceManager.GetString("Tab_Provider_EnrollStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Details.
        /// </summary>
        internal static string Tab_Provider_ExamDetails {
            get {
                return ResourceManager.GetString("Tab_Provider_ExamDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Status.
        /// </summary>
        internal static string Tab_Provider_ExamStatus {
            get {
                return ResourceManager.GetString("Tab_Provider_ExamStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Tab_Provider_Home {
            get {
                return ResourceManager.GetString("Tab_Provider_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor.
        /// </summary>
        internal static string Tab_Provider_Instructor {
            get {
                return ResourceManager.GetString("Tab_Provider_Instructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Tab_Provider_Logout {
            get {
                return ResourceManager.GetString("Tab_Provider_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string Tab_Provider_MyProfile {
            get {
                return ResourceManager.GetString("Tab_Provider_MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Tab_Provider_Reports {
            get {
                return ResourceManager.GetString("Tab_Provider_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        internal static string Tab_Provider_Student {
            get {
                return ResourceManager.GetString("Tab_Provider_Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Student.
        /// </summary>
        internal static string Tab_Provider_Students {
            get {
                return ResourceManager.GetString("Tab_Provider_Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Tab_Student_Home {
            get {
                return ResourceManager.GetString("Tab_Student_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Tab_Student_Logout {
            get {
                return ResourceManager.GetString("Tab_Student_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule/Cancel.
        /// </summary>
        internal static string Tab_Student_MyExams {
            get {
                return ResourceManager.GetString("Tab_Student_MyExams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string Tab_Student_MyProfile {
            get {
                return ResourceManager.GetString("Tab_Student_MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Tab_Student_Reports {
            get {
                return ResourceManager.GetString("Tab_Student_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule an Exam.
        /// </summary>
        internal static string Tab_Student_ReScheduleExam {
            get {
                return ResourceManager.GetString("Tab_Student_ReScheduleExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Exam.
        /// </summary>
        internal static string Tab_Student_ScheduleExam {
            get {
                return ResourceManager.GetString("Tab_Student_ScheduleExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Exam.
        /// </summary>
        internal static string Tab_Student_StartAnExam {
            get {
                return ResourceManager.GetString("Tab_Student_StartAnExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Tools.
        /// </summary>
        internal static string Tab_Student_UploadFiles {
            get {
                return ResourceManager.GetString("Tab_Student_UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web20.
        /// </summary>
        internal static string Telerik_Button_Skin {
            get {
                return ResourceManager.GetString("Telerik_Button_Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web20.
        /// </summary>
        internal static string Telerik_ComboBox_Skin {
            get {
                return ResourceManager.GetString("Telerik_ComboBox_Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GET PASSWORD.
        /// </summary>
        internal static string Telerik_ForgotButton {
            get {
                return ResourceManager.GetString("Telerik_ForgotButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web20.
        /// </summary>
        internal static string Telerik_Grid_Skin {
            get {
                return ResourceManager.GetString("Telerik_Grid_Skin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        internal static string Telerik_Login {
            get {
                return ResourceManager.GetString("Telerik_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTRATION.
        /// </summary>
        internal static string Telerik_Registration {
            get {
                return ResourceManager.GetString("Telerik_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Telerik_Student_Cancel {
            get {
                return ResourceManager.GetString("Telerik_Student_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Telerik_Student_Clear {
            get {
                return ResourceManager.GetString("Telerik_Student_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Telerik_Student_Confirm {
            get {
                return ResourceManager.GetString("Telerik_Student_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Telerik_Student_Delete {
            get {
                return ResourceManager.GetString("Telerik_Student_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Telerik_Student_Next {
            get {
                return ResourceManager.GetString("Telerik_Student_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Telerik_Student_Update {
            get {
                return ResourceManager.GetString("Telerik_Student_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Telerik_Student_Validate {
            get {
                return ResourceManager.GetString("Telerik_Student_Validate", resourceCulture);
            }
        }
    }
}
